terms_0924 = [
    ["Alluvial fan", "沖積扇"],
    ["Bedding", "層理"],
    ["Bedding plane", "層理面"],
    ["Cement", "膠結物"],
    ["Cementation", "膠結作用"],
    ["Chemical sedimentary rocks", "化學沉積岩"],
    ["Chert", "燧石"],
    ["Clastic texture", "碎屑組織"],
    ["Clay", "黏土"],
    ["Coal", "煤"],
    ["Compaction", "壓密作用"],
    ["Conglomerate", "礫岩"],
    ["Contact", "接觸面"],
    ["Cross-beds", "交錯層理"],
    ["Crystalline texture", "晶質構造"],
    ["Crystallization", "結晶作用"],
    ["Deposition", "沉積"],
    ["Detrital sedimentary rocks", "碎屑沉積岩"],
    ["Dolomite", "白雲岩"],
    ["Environment of deposition", "沉積環境"],
    ["Evaporite", "蒸發岩"],
    ["formation", "地層"],
    ["Fossil", "化石"],
    ["Graded bed", "粒級層"],
    ["Gravel", "礫石"],
    ["Limestone", "石灰岩"],
    ["Lithification", "岩化作用"],
    ["Matrix", "基質"],
    ["Mud crack", "泥裂"],
    ["Organic sedimentary rock", "有機沉積岩"],
    ["Original horizontality", "原始水平層理"],
    ["Pore space", "孔隙"],
    ["Recrystallization", "再結晶作用"],
    ["Ripple marks", "波痕"],
    ["Rounding", "圓度"],
    ["Sand", "沙"],
    ["Sandstone", "砂岩"],
    ["Sediment", "沉積物"],
    ["Sedimentary breccia", "沉積角礫岩"],
    ["Sedimentary rocks", "沉積岩"],
    ["Sedimentary structures", "沉積構造"],
    ["Shale", "頁岩"],
    ["Silt", "粉砂"],
    ["Sorting", "淘選"],
    ["Source area", "來源區"],
    ["Transportation", "搬運"],
    ["Turbidity current", "濁流"],
    ["岩化作用", "Lithification"],
    ["粒徑", "Grain size"],
    ["沉積層序", "Sedimentary sequence"],
    ["碎屑沉積岩", "Clastic sedimentary rocks"],
    ["非碎屑沉積岩", "Non-clastic sedimentary rocks"],
    ["泥質沉積岩", "Argillaceous rock"],
    ["壓密作用", "Compaction"],
    ["再結晶作用", "Recrystallization"],
    ["圓度", "Roundness"],
    ["球度", "Sphericity"],
    ["淘選度", "Sorting degree"],
    ["基質", "Matrix"],
    ["沉積環境", "Environment of deposition"],
    ["角礫岩", "Breccia"],
    ["礫岩", "Conglomerate"],
    ["長石砂岩", "Arkose sandstone"],
    ["混濁砂岩", "Graywacke sandstone"],
    ["泥岩", "mudstone"],
    ["濁流", "Turbidity current"],
    ["粉砂岩", "Siltstone"],
    ["層理", "Bedding"],
    ["層理面", "Bedding plane"],
    ["成熟度", "Maturity"],
    ["生物沉積岩", "Biogenic sedimentary rocks"],
    ["生物化學石灰岩", "Biochemical limestone"],
    ["礁灰岩", "Reef limestone"],
    ["化石質石灰岩", "Fossiliferous limestone"],
    ["生物碎屑石灰岩", "Bioclastic limestone"],
    ["殼灰岩", "Coquina"],
    ["微晶石灰岩", "Micritic limestone"],
    ["白堊", "Chalk"],
    ["生物化學燧石岩", "Biochemical chert"],
    ["煤化作用", "Coalification"],
    ["化學沉積岩", "Chemical sedimentary rocks"],
    ["蒸發岩", "Evaporite"],
    ["無機石灰岩", "Inorganic limestone"],
    ["化學石灰岩", "Chemical limestone"],
    ["鮞石質石灰岩", "Oolitic limestone"],
    ["鈣華", "Tufa"],
    ["石灰華", "Travertine"],
    ["洞穴石灰岩", "Speleothem limestone"],
    ["泉華", "sinter"],
    ["白雲岩", "Dolomite"],
    ["帶狀/縞狀鐵礦層", "Banded iron formation"],
    ["磷礦床", "Phosphate deposits"],
    ["海底錳核", "Manganese nodules"],
    ["單層", "Monolayer"],
    ["底形", "Bedform"],
    ["波痕", "Ripple marks"],
    ["水流波痕", "Current ripple marks"],
    ["波浪波痕", "Wave ripple marks"],
    ["壓扁層理", "Flaser bedding"],
    ["透鏡狀層理", "Lenticular bedding"],
    ["波狀層理", "Wavy bedding"],
    ["交錯層理", "Cross-beds"],
    ["平板狀交錯層理", "Planar cross-bedding"],
    ["魚骨狀交錯層理", "Herringbone cross-bedding"],
    ["槽狀交錯層理", "Trough cross-bedding"],
    ["圓丘狀交錯層理", "Dome cross-bedding"],
    ["窪狀交錯層理", "Scour cross-bedding"],
    ["底痕", "Sole marks"],
    ["水道", "Channel"],
    ["荷重鑄型", "Load cast"],
    ["火焰構造", "Flame structure"],
    ["旋捲構造", "Convolute structure"],
    ["碟柱構造", "Dish and pillar structure"],
    ["崩移構造", "Slump structure"],
    ["泥裂", "Mud cracks"],
    ["雨滴痕", "Raindrop imprints"],
    ["沉積盆地", "Sedimentary basin"],
    ["海進", "transgression"],
    ["海退", "regression"]
]

terms_1001 = [
    ["Andesite", "安山岩"],
    ["Aphanitic", "隱晶質"],
    ["Basalt", "玄武岩"],
    ["Batholith", "岩磐(基)"],
    ["Bowen’s reaction series", "包溫反應系列"],
    ["Chill zone", "冷凝區"],
    ["Contact", "接觸面"],
    ["Country rock", "圍岩"],
    ["Crystalline rock", "結晶岩"],
    ["Crystal settling", "晶體沉降"],
    ["Decompression melting", "減壓熔融"],
    ["Diapir", "衝頂作用"],
    ["Differentiation", "分異作用"],
    ["Dike", "岩脈"],
    ["Diorite", "閃長岩"],
    ["Extrusive rock", "噴出岩"],
    ["Felsic (silicic)", "長英質(矽質)"],
    ["Flux melting", "助熔熔融"],
    ["Fragmental rock", "碎屑岩"],
    ["Gabbro", "輝長岩"],
    ["Geothermal gradient", "地溫梯度"],
    ["Glassy rock", "玻璃質岩"],
    ["Granite", "花崗岩"],
    ["Igneous rock", "火成岩"],
    ["Intermediate", "中性"],
    ["Intrusion (intrusive structure)", "侵入作用(侵入構造)"],
    ["Intrusive rock", "侵入岩"],
    ["Komatiite", "科馬提岩"],
    ["Lava", "熔岩"],
    ["Mafic", "鎂鐵質"],
    ["Magma", "岩漿"],
    ["Mantle plume", "地函柱"],
    ["Obsidian", "黑曜岩"],
    ["Pegmatite", "偉晶岩"],
    ["Peridotite", "橄欖岩"],
    ["Phaneritic", "顯晶質"],
    ["Phenocryst", "斑晶"],
    ["Pluton", "深成岩體"],
    ["Plutonic rock", "深成岩"],
    ["Porphyritic", "斑狀(組織)"],
    ["Pumice", "浮石"],
    ["Pyroclasts (tephra)", "火山碎屑(岩)"],
    ["Rhyolite", "流紋岩"],
    ["Rock", "岩石"],
    ["Scoria", "岩渣；火山渣"],
    ["Sill", "岩床"],
    ["Stock", "岩株"],
    ["Texture", "質地；組織"],
    ["Tuff", "凝灰岩"],
    ["Ultramafic rock", "超鎂鐵質岩"],
    ["Vesicles", "氣泡"],
    ["Volcanic breccia", "火山角礫岩"],
    ["Volcanic neck", "火山頸"],
    ["Xenolith", "捕獲石"],
    ["岩漿", "Magma"],
    ["地溫梯度", "Geothermal gradient"],
    ["岩石圈", "Lithosphere"],
    ["軟流圈", "Asthenosphere"],
    ["中洋脊", "Mid-ocean ridge"],
    ["熱點（地函柱）", "Hotspot(Mantle plume)"],
    ["地函楔", "Mantle wedge"],
    ["島弧", "Island arc"],
    ["黏性", "Viscosity"],
    ["玄武岩質岩漿", "Basaltic magma"],
    ["安山岩質岩漿", "Andesitic magma"],
    ["流紋岩質岩漿", "Rhyolitic magma"],
    ["頂蝕作用", "overhand stoping"],
    ["衝頂作用", "diapir"],
    ["岩脈作用", "dyking"],
    ["熔結凝灰岩", "Ignimbrite"],
    ["枕狀熔岩", "Pillow lava"],
    ["包溫反應系列", "Bowen's reaction series"],
    ["上部地函", "Upper mantle"],
    ["結晶分異作用", "Crystallization differentiation"],
    ["聚晶組織", "synneusis texture"],
    ["純橄欖岩", "Pure peridotite"],
    ["聚晶岩", "Intergrown rock"],
    ["造岩礦物", "Rock forming minerals"],
    ["火山岩", "Volcanic rock"],
    ["噴出岩", "Extrusive rock"],
    ["深成岩", "Plutonic rock"],
    ["侵入岩", "Intrusive rock"],
    ["淺成岩", "Hypabyssal rock"],
    ["岩脈", "Dike"],
    ["整合貫入", "concordant injections"],
    ["岩床", "Sill"],
    ["岩蓋", "Laccolith"],
    ["岩盆", "lopolith"],
    ["不整合貫入", "Discordant injections"],
    ["岩株", "Stock"],
    ["岩基", "Batholith"],
    ["地盾", "Shield"],
    ["全晶質", "Holocrystalline"],
    ["全玻質", "Holohyaline"],
    ["斑晶", "Phenocryst"],
    ["石基", "Groundmass"],
    ["斑狀組織", "Porphyritic (texture)"],
    ["顯晶質", "Phaneritic"],
    ["隱晶質", "Aphanitic"],
    ["自形", "idiomorphism"],
    ["他形", "Anhedral"],
    ["半自形", "Subhedral"],
    ["輝綠結構", "Diabase texture"],
    ["粗面構造", "Trachyte structure"],
    ["文象組織", "Fabric"],
    ["崩解張裂作用", "Decompression fissuring"],
    ["A’a", "阿Y熔岩"],
    ["Active volcano", "活火山"],
    ["Ash", "火山灰"],
    ["Block", "火山塊"],
    ["Bomb", "火山彈"],
    ["Caldera", "破火山口；火山臼"],
    ["Cinder", "火山渣"],
    ["Cinder cone", "火山渣錐"],
    ["Circum-Pacific belt", "環太平洋帶"],
    ["Columnar jointing", "柱狀節理"],
    ["Composite volcano", "複式火山"],
    ["Stratovolcano", "錐狀火山"],
    ["Crater", "火山口"],
    ["Dormant volcano", "休火山"],
    ["Dust", "火山塵埃"],
    ["Effusive eruption", "噴溢噴發"],
    ["Explosive eruption", "爆裂噴發"],
    ["Pyroclastic eruption", "火山碎屑噴發"],
    ["Extinct volcano", "死火山"],
    ["Flank eruption", "山側噴發"],
    ["Flood basalt", "洪流式玄武岩"],
    ["Lahar", "火山泥流"],
    ["Lapilli", "火山礫"],
    ["Lava dome", "熔岩穹丘"],
    ["Lava tube", "熔岩管"],
    ["Mediterranean belt", "地中海帶"],
    ["Pahoehoe", "繩狀熔岩"],
    ["Pillow lava", "枕狀熔岩"],
    ["Pyroclast", "火山碎屑(岩)"],
    ["Pyroclastic flow", "火山碎屑流"],
    ["Shield volcano", "盾狀火山"],
    ["Vent", "火山口"],
    ["Viscosity", "黏性"],
    ["Volcanic Explosivity Index", "火山爆發指數"],
    ["Volcanism", "火山作用"],
    ["Volcano", "火山"],
    ["十年火山", "Decade volcano"],
    ["中洋脊", "Mid-ocean ridge"],
    ["洪流式玄武岩", "Flood basalt"],
    ["隱沒帶", "Subduction zone"],
    ["活火山", "Active volcano"],
    ["地函柱", "Mantle plume"],
    ["爆發作用", "Eruption"],
    ["噴溢作用", "Effusion"],
    ["岩漿噴發", "Magma eruption"],
    ["噴發柱", "Eruption column"],
    ["蒸氣岩漿噴發", "Phreatomagmatic eruption"],
    ["蒸氣噴發", "Phreatic eruption"],
    ["枕狀熔岩", "Pillow lava"],
    ["中心式噴發", "Central eruption"],
    ["裂隙式噴發", "Fissure eruption"],
    ["區域性噴發", "Regional eruption"],
    ["夏威夷式", "Hawaiian"],
    ["斯通波利式", "Strombolian"],
    ["火山島式", "Vulcanian"],
    ["維蘇威式", "Vesuvian"],
    ["培雷式", "Pelean"],
    ["普林尼式", "Plinian"],
    ["火山雲", "Volcanic cloud"],
    ["盾狀火山", "Shield volcano"],
    ["錐狀火山", "Stratovolcano"],
    ["複式火山", "Composite volcano"],
    ["爆裂火山口", "Explosive crater"],
    ["陷落火山口", "Caldera"],
    ["沉陷火山口", "cauldron"],
    ["熔岩穹丘", "Lava dome"],
    ["繩狀熔岩", "Pahoehoe"],
    ["阿Y熔岩", "A'a lava"],
    ["塊狀熔岩", "Blocky lava"],
    ["熱螢光定年", "Thermoluminescence dating"]
]

terms_1008 = [
    ["A horizon", "A化育層(表土層)"],
    ["B horizon (zone of accumulation)", "澱積層"],
    ["C horizon", "C化育層(風化層)"],
    ["Chemical weathering", "化學風化"],
    ["Clay mineral", "黏土礦物"],
    ["Differential weathering", "差異風化"],
    ["E horizon (zone of leaching)", "淋溶層"],
    ["Erosion", "侵蝕作用"],
    ["Exfoliation", "剝離作用"],
    ["Exfoliation dome", "剝離丘"],
    ["Frost action", "冰凍作用"],
    ["Frost heaving", "冰舉作用"],
    ["Frost wedging", "冰楔作用"],
    ["Hematite", "赤鐵礦"],
    ["Limonite", "褐鐵礦"],
    ["Loam", "壤土"],
    ["Mechanical weathering", "機械風化"],
    ["O horizon", "O化育層(有機質層)"],
    ["Pressure release", "壓力釋放"],
    ["Residual soil", "殘積土"],
    ["Sheet joints", "頁狀節理"],
    ["Soil", "土壤"],
    ["Soil horizon", "土壤化育層"],
    ["Spheroidal weathering", "球狀風化"],
    ["Transportation", "搬運作用"],
    ["Transported soil", "還積土"],
    ["Weathering", "風化作用"],
    ["岩屑層", "regolith(rock mantle)"],
    ["風化層", "regolith"],
    ["土壤", "Soil"],
    ["碎屑物質", "Clastic material"],
    ["節理作用", "Jointing"],
    ["剝露作用", "Exhumation"],
    ["節理面", "Joint plane"],
    ["剝離作用", "Exfoliation"],
    ["冰楔作用", "Frost wedging"],
    ["鹽楔作用", "Salt wedging"],
    ["根楔作用", "Root wedging"],
    ["溶解作用", "Dissolution"],
    ["碳酸鹽岩", "Carbonate rock"],
    ["水解作用", "Hydrolysis"],
    ["氧化作用", "Oxidation"],
    ["水合作用", "Hydration"],
    ["風化殼", "weathered crust"],
    ["腐植質", "Humus"],
    ["淋溶層", "zone of leaching(E horizon)"],
    ["澱積層", "zone of accumulation(B horizon)"],
    ["土壤化育層", "soil horizon"],
    ["土壤剖面", "soil profile"],
    ["表土", "surface soil"],
    ["心土", "Subsoil"],
    ["土體", "solum"],
    ["K層", "zone of carbonate(K horizon)"],
    ["土壤組織", "Soil texture"],
    ["土壤結構", "Soil structure"],
    ["鈣層土", "pedocal"],
    ["鐵鋁土", "pedalfer"],
    ["紅土", "Laterite"],
    ["古土壤", "paleosol"],
    ["石英砂岩", "quartz arenite"],
    ["頁岩", "Shale"]
]

terms_1014 = [
    ["Compressive stress", "壓應力"],
    ["Confining pressure", "圍壓"],
    ["Contact metamorphism", "接觸變質作用"],
    ["Differential stress", "差異應力"],
    ["Ductile (plastic)", "延展性(可塑性)"],
    ["Foliation", "葉理"],
    ["Gneiss", "片麻岩"],
    ["Hornfels", "角頁岩"],
    ["Hydrothermal metamorphism", "熱液變質作用"],
    ["Isotherm", "等溫線"],
    ["Marble", "大理岩"],
    ["Metamorphic facies", "變質相"],
    ["Metamorphic rock", "變質岩"],
    ["Metamorphism", "變質作用"],
    ["Metasomatism", "換質作用"],
    ["Migmatite", "混成岩"],
    ["Parent rock (protolith)", "母岩"],
    ["Phyllite", "千枚岩"],
    ["Quartzite", "石英岩"],
    ["Regional metamorphism", "區域變質作用"],
    ["Schist", "片岩"],
    ["Shearing", "剪切作用"],
    ["Slate", "板岩"],
    ["Stress", "應力"],
    ["Vein", "礦脈"],
    ["大理岩", "Marble"],
    ["片岩", "Schist"],
    ["片麻岩", "Gneiss"],
    ["石英岩", "Quartzite"],
    ["正應力", "normal stress"],
    ["再結晶作用", "Recrystallization"],
    ["角頁岩", "Hornfels"],
    ["角閃岩", "Amphibolite"],
    ["板岩", "Slate"],
    ["岩石循環", "Rock cycle"],
    ["矽線石", "Zenolite(Sillimanite)"],
    ["指標礦物", "Index mineral"],
    ["紅柱石", "Andalusite"],
    ["差異剪力", "Differential shear stress"],
    ["埋藏變質作用", "Burial metamorphism"],
    ["剝露作用", "Exhumation"],
    ["剪應力", "Shear stress"],
    ["退化變質作用", "regressive metamorphism"],
    ["區域變質作用", "Regional metamorphism"],
    ["混合岩", "Migmatite"],
    ["蛇紋岩", "Serpentinite"],
    ["接觸變質作用", "Contact metamorphism"],
    ["換質作用", "Metasomatism"],
    ["等變質度線", "Isograd"],
    ["進化變質作用", "Prograde metamorphism"],
    ["超高溫變質作用", "Ultrahigh temperature metamorphism"],
    ["超高壓變質作用", "Ultrahigh pressure metamorphism"],
    ["葉理", "Foliation"],
    ["綠片岩", "Greenschist"],
    ["榴輝岩", "Eclogite"],
    ["撞擊變質作用", "aethoballism"],
    ["熱液變質作用", "Hydrothermal metamorphism"],
    ["壓溶作用", "Pressure solution"],
    ["壓溫時軌跡", "P-T-t path"],
    ["糜稜岩", "Mylonite"],
    ["隱沒帶變質作用", "Subduction zone metamorphism"],
    ["藍閃石", "Glaucophane"],
    ["藍晶石", "Kyanite"],
    ["礦物共生組合", "aragenetic assemblage of minerals"],
    ["變質作用", "Metamorphism"],
    ["變質岩", "Metamorphic rock"],
    ["變質相", "Metamorphic facies"],
    ["變質帶", "zone of metamorphism"],
    ["變質斑晶", "porphyroblast"],
    ["岩理", "Rock texture"],
    ["變質葉理", "Metamorphic foliation"],
    ["動熱變質作用", "dynamothermal metamorphism"],
    ["巴羅型變質作用", "Barrovian metamorphism"]
]
